"""empty message

Revision ID: 60e8cdd90b57
Revises: 83c3e8ec24cb
Create Date: 2023-02-17 19:52:08.743671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60e8cdd90b57'
down_revision = '83c3e8ec24cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog__user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hobby', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('desc', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog__user', schema=None) as batch_op:
        batch_op.drop_column('address')
        batch_op.drop_column('email')
        batch_op.drop_column('gender')
        batch_op.drop_column('desc')
        batch_op.drop_column('hobby')

    # ### end Alembic commands ###
